### ISSUE TITLE
Review setup instructions

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-server#15]
Setup instructions for the Tau Camera are here: https://github.com/OnionIoT/tau-lidar-server/blob/master/GET-STARTED.md

All 3 modules are live on PIP, so please try out the instructions as if you were a new user. 
Feel free to edit, expand, adjust as you see fit!

**Comment by greenbreakfast** [comment]
@VSemi-Zhen please try it out and let us know how it goes!

**Comment by VSemi-Zhen** [comment]
there should be a python download link in the instruction
I recommend the following text.

To use the Tau Studio Web App, you'll need to have Python and TauLidarServer installed.
1. install python
	Download and install python at https://www.python.org/downloads/. Make sure you install version 3.6.1 or higher. If you 
        have questions about python installation, further instructions can be found at the official Python.org instructions 
2. install TauLidarServer Python module
	Open a command-line window, and run the following command:
	python -m pip install TauLidarServer

**Comment by greenbreakfast** [comment]
@VSemi-Zhen sounds good. Please make the changes: https://github.com/OnionIoT/tau-lidar-server/blob/master/GET-STARTED.md

**Comment by greenbreakfast** [comment]
Made some updates to make the text seem friendly. 
Closing this issue. Captured outstanding image todos in #18
