### ISSUE TITLE
User can enable depth map view of camera frames

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-server#16]
## User Story

* User starts TauLidarServer and navigates to web-based point-cloud viewer
* User clicks "Depth Map View" button in sidebar
* Observe modal appears showing real-time amplitude view of frames from camera

**Comment by mh1412** [comment]
# Implementation plan 
- Changing server side code to send multiple frame types along side the point cloud data
- Adding picture in picture view to the side of the display to show depth map view
