### ISSUE TITLE
User can also see greyscale image in the Web Viewer

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-server#2]
# User Story

1. User starts TauLidarServer and navigates to web-based point-cloud viewer
1. Observe 3D point-cloud rendering of camera output is displayed, along with smaller picture-in-picture view of the greyscale image from the camera

# Background

Will help users interpret the 3D point cloud visualization

**Comment by mh1412** [comment]
# Implementation plan 
- Adding picture in picture view to the side of the display to show greyscale (amplitude) view
- Greyscale view will automatically show up without the need to click any button 
- Changing server side code to send multiple frame types along side the point cloud data
  - Server will send greyscale data in json array
  - web app will parse the array data and construct images on the fly
