### ISSUE TITLE
Make links in README.md absolute

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-server#20]
In order to work properly with PyPi project description, all links in top-level README.md need to be absolute

See https://pypi.org/project/TauLidarServer/, Notice how:

* Tau Studio screenshot is a broken link
* Link to DEVELOPMENT.md is broken

**Comment by dgabriel123** [comment]
Hello, may I tackle this one?

**Comment by greenbreakfast** [comment]
Done in PR #21 
Thanks @dgabriel123 !
